diesel-car-small=142
petrol-car-small=154
plugin-hybrid-car-small=73
electric-car-small=50
diesel-car-medium=171
petrol-car-medium=192
plugin-hybrid-car-medium=110
electric-car-medium=58
diesel-car-large=209
petrol-car-large=282
plugin-hybrid-car-large=126
electric-car-large=73
bus-default=27
train-default=6
